/* Product catalogue data — single source of truth for product pages,
   catalogue cards, scene/floorplan SVGs and Product schema.

   Specifications are taken from the manufacturer's order sheets for
   Model 0206 (AU standard, 240V). Manufacturer cost pricing is
   confidential — the site never displays prices; every CTA leads to a
   delivered-quote request. */

export const products = [
  {
    slug: "model-0206-two-bedroom-white",
    name: "Model 0206 Two-Bedroom — Classic White",
    series: "Model 0206 Range",
    badge: "Two Bedrooms",
    tagline: "A crisp, light-filled two-bedroom expandable.",
    intro:
      "Two genuine bedrooms, a fitted kitchen and a full bathroom in one expandable home. The Classic White edition pairs clean white wall panels with a light grey frame for a bright, timeless exterior.",
    bedrooms: 2,
    bathrooms: 1,
    sleeps: 4,
    closed: "standard road width",
    expanded: "its full two-bedroom footprint",
    planNote: "Final dimensions are confirmed with your order specification and included in your delivered quote.",
    leadTime: "confirmed with your quote",
    audience: ["Granny flats", "First home buyers", "Rural blocks", "Guest accommodation"],
    palette: "day",
    sceneWidth: 560,
    photos: {
      card: "white-cutout.webp",
      cardAlt: "Model 0206 Classic White expandable home with grid-design windows",
      hero: "white-cutout.webp",
      heroAlt: "Model 0206 Classic White expandable home, expanded, with white grid-design windows and grey frame",
      gallery: [
        ["white-factory-1.webp", "Model 0206 Classic White fully expanded during factory inspection"],
        ["interior-dining.webp", "Dining and kitchen area with white cabinetry inside the Model 0206"],
        ["interior-kitchen.webp", "Fitted kitchen with cabinetry, oven and fridge inside the Model 0206"],
        ["interior-living.webp", "Living area with sofa and double glass doors inside the Model 0206"],
        ["interior-bedroom.webp", "Furnished bedroom with double bed and curtains inside the Model 0206"],
        ["interior-bathroom.webp", "Bathroom with shower, toilet and washing machine space in the Model 0206"],
        ["white-front.webp", "Front elevation of the Model 0206 Classic White with both wings expanded and double doors open"],
      ],
    },
    features: [
      ["Two real bedrooms", "Separate bedrooms with real walls and real doors — not lofts or fold-out beds. Room for a couple plus kids, guests or a home office."],
      ["Complete kitchen & bathroom", "Fitted kitchen cabinetry, plus a full bathroom with toilet, basin and shower — a complete, self-contained home as delivered."],
      ["Double-glazed openings", "Double-glazed door and window keep summer heat out and winter warmth in, with grid-net design windows and white net shades."],
      ["Fire-resistant wall panels", "50mm fire-resistant EPS insulated wall panels on a welded steel frame — light to transport, quick to expand, easy to keep comfortable."],
    ],
    included: [
      "Two bedrooms with real walls and doors",
      "Kitchen with fitted cabinetry",
      "Bathroom with toilet, basin and shower",
      "50mm fire-resistant EPS wall panels, white",
      "Steel frame finished in RAL 7015 grey",
      "Double-glazed door and window",
      "Plastic-steel windows, grid-net design, white net shades",
      "Entrance door — grey exterior, white interior",
      "016 PVC flooring throughout",
      "Australian-standard 240V electrical",
    ],
    specs: [
      ["Layout", "2 bedrooms, kitchen, bathroom"],
      ["Wall panels", "50mm fire-resistant EPS, white"],
      ["Frame", "Steel, RAL 7015 grey"],
      ["Glazing", "Double-glazed door and window"],
      ["Windows", "Plastic-steel, grid-net design, white net shade"],
      ["Entrance door", "RAL 7015 grey exterior, white interior"],
      ["Flooring", "016 PVC"],
      ["Electrical", "Australian standard, 240V"],
      ["Dimensions", "Confirmed with order specification"],
    ],
    floorplan: [
      { x: 0, y: 0, w: 38, h: 32, label: "Kitchen" },
      { x: 0, y: 32, w: 38, h: 68, label: "Living / Dining" },
      { x: 38, y: 0, w: 24, h: 46, label: "Bathroom" },
      { x: 38, y: 46, w: 24, h: 54, label: "Entry" },
      { x: 62, y: 0, w: 38, h: 58, label: "Bedroom 1" },
      { x: 62, y: 58, w: 38, h: 42, label: "Bedroom 2" },
    ],
    faqs: [
      ["Is the Model 0206 suitable as a granny flat?", "Yes — with two bedrooms, a kitchen and a full bathroom it's a complete secondary dwelling. Approval requirements depend on your state and block; we supply the specification documents your certifier needs."],
      ["What arrives on the truck?", "The complete home, folded to standard road width — bedrooms, kitchen cabinetry, bathroom, flooring, wiring and glazing already fitted. On site it expands to its full footprint and is connected to services."],
      ["Can I see exact dimensions and a detailed floor plan?", "Yes — request a quote and we'll send the full specification sheet and dimensioned floor plan for the current production version, along with delivered pricing for your postcode."],
    ],
  },
  {
    slug: "model-0206-two-bedroom-black",
    name: "Model 0206 Two-Bedroom — Black Edition",
    series: "Model 0206 Range",
    badge: "Premium Cladding",
    tagline: "Architectural black frame. Feature-clad exterior.",
    intro:
      "The same two-bedroom layout, elevated: a matte black RAL 9011 frame, thermal-break aluminium windows and a 20mm feature-clad exterior that reads as architectural rather than transportable.",
    bedrooms: 2,
    bathrooms: 1,
    sleeps: 4,
    closed: "standard road width",
    expanded: "its full two-bedroom footprint",
    planNote: "Final dimensions are confirmed with your order specification and included in your delivered quote.",
    leadTime: "confirmed with your quote",
    audience: ["Airbnb & farm stays", "Premium granny flats", "Design-led buyers", "Guest accommodation"],
    palette: "dusk",
    sceneWidth: 580,
    photos: {
      card: "hero-backyard.webp",
      cardAlt: "Model 0206 Black Edition with timber-look cladding installed in a backyard",
      hero: "hero-backyard.webp",
      heroAlt: "Model 0206 Black Edition expanded in a landscaped backyard with outdoor chairs",
      gallery: [
        ["black-backyard-angle.webp", "Model 0206 Black Edition timber-look cladding from the side, installed on a lawn"],
        ["interior-living.webp", "Living area with sofa inside the Model 0206"],
        ["interior-kitchen.webp", "Fitted kitchen with cabinetry, oven and fridge inside the Model 0206"],
        ["interior-dining.webp", "Dining and kitchen area with white cabinetry inside the Model 0206"],
        ["interior-bedroom.webp", "Furnished bedroom with double bed and curtains inside the Model 0206"],
        ["interior-bathroom.webp", "Bathroom with shower and toilet in the Model 0206"],
        ["black-factory-1.webp", "Model 0206 Black Edition expanded during factory pre-shipment inspection"],
      ],
    },
    features: [
      ["Feature-clad exterior", "50mm fire-resistant EPS panels finished with 20mm exterior feature cladding — the profile that makes guests and neighbours assume it's a site-built studio."],
      ["Thermal-break aluminium windows", "RAL 9011 black aluminium windows with thermal-break frames and fitted fly screens — better thermal performance and a sharper sightline."],
      ["Black-on-black detailing", "Frame, entrance door and window frames all finished in matte RAL 9011 black for a consistent architectural look."],
      ["Same complete layout", "Two bedrooms, fitted kitchen and full bathroom with toilet, basin and shower — identical liveability to the Classic White."],
    ],
    included: [
      "Two bedrooms with real walls and doors",
      "Kitchen with fitted cabinetry",
      "Bathroom with toilet, basin and shower",
      "50mm fire-resistant EPS wall panels",
      "20mm exterior feature cladding",
      "Steel frame finished in RAL 9011 black",
      "Thermal-break aluminium windows with fly screens",
      "Black entrance door, RAL 9011",
      "016 PVC flooring throughout",
      "Australian-standard 240V electrical",
    ],
    specs: [
      ["Layout", "2 bedrooms, kitchen, bathroom"],
      ["Wall panels", "50mm fire-resistant EPS + 20mm feature cladding"],
      ["Frame", "Steel, RAL 9011 black"],
      ["Glazing", "Double-glazed door and window"],
      ["Windows", "RAL 9011 thermal-break aluminium, fly screens"],
      ["Entrance door", "RAL 9011 black"],
      ["Flooring", "016 PVC"],
      ["Electrical", "Australian standard, 240V"],
      ["Dimensions", "Confirmed with order specification"],
    ],
    floorplan: [
      { x: 0, y: 0, w: 38, h: 32, label: "Kitchen" },
      { x: 0, y: 32, w: 38, h: 68, label: "Living / Dining" },
      { x: 38, y: 0, w: 24, h: 46, label: "Bathroom" },
      { x: 38, y: 46, w: 24, h: 54, label: "Entry" },
      { x: 62, y: 0, w: 38, h: 58, label: "Bedroom 1" },
      { x: 62, y: 58, w: 38, h: 42, label: "Bedroom 2" },
    ],
    faqs: [
      ["What's different from the Classic White?", "The layout is identical — the difference is the exterior and window package: 20mm feature cladding over the EPS panels, a black RAL 9011 frame and entrance door, and thermal-break aluminium windows with fly screens instead of plastic-steel."],
      ["Why choose thermal-break aluminium windows?", "The frame has an insulating barrier between inside and outside faces, cutting heat transfer and condensation — a meaningful comfort upgrade in hot summers and cold mornings alike."],
      ["Is it suited to short-stay accommodation?", "It's the finish we'd pick for it: the clad exterior photographs like an architectural cabin, and the black window frames give listings the look guests expect at premium nightly rates."],
    ],
  },
];
