/* Product catalogue data — single source of truth for product pages,
   catalogue cards, scene/floorplan SVGs and Product schema. */

export const products = [
  {
    slug: "20ft-expandable-tiny-home",
    name: "20ft Expandable Tiny Home",
    series: "Essential Series",
    badge: "Best Seller",
    tagline: "Big living from a single delivery.",
    intro:
      "Arrives folded on one truck. Expands to a light-filled one-bedroom home with a full kitchen and bathroom — set up and liveable in days, not months.",
    price: 34900,
    priceNote: "delivered pricing quoted per postcode",
    bedrooms: 1,
    bathrooms: 1,
    sleeps: 2,
    closed: "6.0m × 2.5m",
    expanded: "6.0m × 6.6m",
    area: 39,
    height: "2.6m internal ceiling",
    weight: "≈ 5.2 tonnes",
    leadTime: "10–14 weeks",
    audience: ["First home buyers", "Backyard living", "Rural blocks", "Granny flat alternative"],
    palette: "dusk",
    features: [
      ["Fold-out design", "Both wings expand in under 3 hours with a two-person crew — no crane required on standard sites."],
      ["Full-size kitchen", "Stone-look benchtops, soft-close cabinetry, 4-burner cooktop, rangehood and space for a full-height fridge."],
      ["Hotel-grade bathroom", "Frameless glass shower, wall-hung vanity, ceramic tiles and quality tapware as standard."],
      ["Double-glazed throughout", "Aluminium double-glazed windows and sliding doors keep summer heat out and winter warmth in."],
    ],
    included: [
      "Structural steel frame, fully welded and galvanised",
      "100mm insulated wall, roof and floor panels",
      "Double-glazed windows and sliding doors",
      "Complete kitchen with cabinetry and cooktop",
      "Full bathroom with shower, toilet and vanity",
      "Reverse-cycle split system air conditioner",
      "LED downlights and power points throughout",
      "Smoke alarms and switchboard with safety switches",
      "Vinyl plank flooring, fully finished walls",
      "Externally rated power inlet and water connections",
    ],
    upgrades: [
      ["Off-grid solar + battery package", "from $12,500"],
      ["Composting toilet system", "from $2,400"],
      ["Premium façade cladding", "from $4,800"],
      ["Awning + deck kit", "from $6,900"],
      ["Furniture package (turnkey)", "from $7,500"],
    ],
    specs: [
      ["Transport dimensions", "6.0m L × 2.5m W × 2.9m H"],
      ["Expanded footprint", "6.0m L × 6.6m W"],
      ["Internal floor area", "39m²"],
      ["Structure", "Galvanised steel frame, insulated sandwich panels"],
      ["Wind rating", "Engineered to AS/NZS 1170 (site-specific tie-downs)"],
      ["Electrical", "240V, 15A inlet, compliant switchboard"],
      ["Plumbing", "Standard connections for mains, tank or septic"],
      ["Warranty", "10-year structural, 2-year fixtures and fittings"],
    ],
    floorplan: [
      { x: 0, y: 0, w: 30, h: 100, label: "Bedroom" },
      { x: 30, y: 0, w: 42, h: 100, label: "Living / Dining" },
      { x: 72, y: 0, w: 28, h: 55, label: "Kitchen" },
      { x: 72, y: 55, w: 28, h: 45, label: "Bathroom" },
    ],
    faqs: [
      ["How long does the 20ft take to set up?", "Most installs are complete in a single day: the home is positioned in the morning, both wings folded out within about three hours, then services connected. Weather-tight the same day."],
      ["Do I need a crane?", "Usually not. On level, accessible sites the home slides off a tilt-tray truck. Sloping or tight-access sites may need a crane or Franna — we confirm this during your free site assessment."],
      ["Can two people live in it comfortably?", "Yes. With a separate bedroom, full kitchen and 39m² expanded, it lives like a compact one-bedroom apartment — most couples find it far roomier than they expect."],
    ],
  },
  {
    slug: "40ft-expandable-tiny-home",
    name: "40ft Expandable Tiny Home",
    series: "Grand Series",
    badge: "Most Space",
    tagline: "A genuine family home that arrives on one truck.",
    intro:
      "Two to three bedrooms, two bathrooms and open-plan living across 78m². The 40ft is our answer to people who thought they needed a site build.",
    price: 59900,
    priceNote: "delivered pricing quoted per postcode",
    bedrooms: 3,
    bathrooms: 2,
    sleeps: 6,
    closed: "12.0m × 2.5m",
    expanded: "12.0m × 6.6m",
    area: 78,
    height: "2.6m internal ceiling",
    weight: "≈ 9.8 tonnes",
    leadTime: "12–16 weeks",
    audience: ["Families", "Rural property owners", "Primary residence", "Workforce accommodation"],
    palette: "day",
    features: [
      ["Three true bedrooms", "A master with room for a queen plus two additional bedrooms — not lofts, not fold-outs. Real rooms with real doors."],
      ["Two full bathrooms", "A private ensuite off the master and a family bathroom with laundry provisions."],
      ["Open-plan heart", "Over 30m² of kitchen, dining and living space with a full glass wall to your outlook."],
      ["One delivery, one day", "Despite the size, the 40ft still transports as a single standard load and expands on site in under a day."],
    ],
    included: [
      "Structural steel frame, fully welded and galvanised",
      "100mm insulated wall, roof and floor panels",
      "Double-glazed windows and stacker sliding doors",
      "Full kitchen with island bench and 900mm cooktop",
      "Two complete bathrooms including ensuite",
      "Two reverse-cycle split system air conditioners",
      "European laundry provisions with cabinetry",
      "LED lighting, power and data points throughout",
      "Smoke alarms and compliant switchboard",
      "Vinyl plank flooring, square-set finished walls",
    ],
    upgrades: [
      ["Off-grid solar + battery package", "from $18,500"],
      ["Butler's pantry joinery kit", "from $4,200"],
      ["Premium façade cladding", "from $7,900"],
      ["Wrap-around deck + awning kit", "from $11,500"],
      ["Furniture package (turnkey)", "from $12,900"],
    ],
    specs: [
      ["Transport dimensions", "12.0m L × 2.5m W × 2.9m H"],
      ["Expanded footprint", "12.0m L × 6.6m W"],
      ["Internal floor area", "78m²"],
      ["Structure", "Galvanised steel frame, insulated sandwich panels"],
      ["Wind rating", "Engineered to AS/NZS 1170 (site-specific tie-downs)"],
      ["Electrical", "240V, 2 × 15A or hardwired, compliant switchboard"],
      ["Plumbing", "Standard connections for mains, tank or septic"],
      ["Warranty", "10-year structural, 2-year fixtures and fittings"],
    ],
    floorplan: [
      { x: 0, y: 0, w: 20, h: 100, label: "Master + Ensuite" },
      { x: 20, y: 0, w: 38, h: 100, label: "Living / Dining" },
      { x: 58, y: 0, w: 16, h: 100, label: "Kitchen" },
      { x: 74, y: 0, w: 13, h: 50, label: "Bed 2" },
      { x: 74, y: 50, w: 13, h: 50, label: "Bed 3" },
      { x: 87, y: 0, w: 13, h: 100, label: "Bath / Laundry" },
    ],
    faqs: [
      ["Is the 40ft big enough as a permanent family home?", "Yes — at 78m² with three bedrooms and two bathrooms it's comparable to many two-to-three bedroom apartments. Hundreds of Australian families live in homes this size full-time."],
      ["Does it need council approval?", "As a permanent dwelling, almost always yes — either as a secondary dwelling or primary residence depending on your block. We supply engineering drawings and documentation to support your application, and can refer you to private certifiers."],
      ["Can it be transported to rural properties?", "Absolutely. It travels as a standard 12m load. For remote sites we quote transport precisely by postcode, and our carriers routinely deliver to farms and stations in every state."],
    ],
  },
  {
    slug: "luxury-series",
    name: "Luxury Series Expandable Home",
    series: "Signature Range",
    badge: "Flagship",
    tagline: "Architectural finishes. Uncompromising detail.",
    intro:
      "Our flagship. Engineered stone benchtops, oak-look feature joinery, brushed-brass tapware, hidden lighting and a bathroom you'd expect in a boutique hotel.",
    price: 79900,
    priceNote: "delivered pricing quoted per postcode",
    bedrooms: 2,
    bathrooms: 2,
    sleeps: 4,
    closed: "12.0m × 2.5m",
    expanded: "12.0m × 6.6m",
    area: 78,
    height: "2.7m internal ceiling",
    weight: "≈ 10.4 tonnes",
    leadTime: "14–18 weeks",
    audience: ["Luxury accommodation", "Executive retreats", "Premium Airbnb", "Downsizers"],
    palette: "dusk",
    features: [
      ["Signature interior palette", "Engineered stone, matte-black or brushed-brass hardware, oak-look joinery and designer pendant lighting as standard."],
      ["Spa-grade bathrooms", "Full-height tiling, rainfall showers, backlit mirrors and wall-hung vanities in both bathrooms."],
      ["Climate perfected", "Upgraded insulation, ducted-style concealed air conditioning and ceiling fans for silent comfort."],
      ["A ceiling that changes everything", "2.7m ceilings with square-set cornices and concealed LED strip lighting — the single biggest reason guests say it doesn't feel tiny."],
    ],
    included: [
      "Everything in the Grand Series specification, plus:",
      "Engineered stone benchtops throughout",
      "Premium appliance package (oven, dishwasher, integrated rangehood)",
      "Full-height bathroom tiling with rainfall showers",
      "Concealed LED strip and designer pendant lighting",
      "Upgraded acoustic and thermal insulation",
      "Brushed-brass or matte-black tapware and hardware",
      "Feature timber-look ceiling battens to living area",
      "Sheer + blockout curtain package",
      "External hot/cold shower point",
    ],
    upgrades: [
      ["Plunge pool + deck integration kit", "from $24,000"],
      ["Outdoor kitchen module", "from $9,800"],
      ["Full off-grid autonomy package", "from $21,500"],
      ["Smart home automation pack", "from $4,900"],
      ["Custom interior design consultation", "from $2,500"],
    ],
    specs: [
      ["Transport dimensions", "12.0m L × 2.5m W × 3.0m H"],
      ["Expanded footprint", "12.0m L × 6.6m W"],
      ["Internal floor area", "78m²"],
      ["Ceiling height", "2.7m square-set"],
      ["Structure", "Galvanised steel frame, upgraded insulated panels"],
      ["Wind rating", "Engineered to AS/NZS 1170 (site-specific tie-downs)"],
      ["Electrical", "240V hardwired, smart-ready switchboard"],
      ["Warranty", "10-year structural, 3-year fixtures and fittings"],
    ],
    floorplan: [
      { x: 0, y: 0, w: 24, h: 100, label: "Master Suite" },
      { x: 24, y: 0, w: 40, h: 100, label: "Living / Dining" },
      { x: 64, y: 0, w: 18, h: 100, label: "Kitchen" },
      { x: 82, y: 0, w: 18, h: 55, label: "Bed 2" },
      { x: 82, y: 55, w: 18, h: 45, label: "Bathroom" },
    ],
    faqs: [
      ["What makes the Luxury Series different from the 40ft?", "The shell is similar — the experience is not. Higher ceilings, stone surfaces, premium appliances, full-height tiling, concealed lighting and upgraded insulation transform how the space looks, sounds and feels."],
      ["Is it suitable for luxury short-stay accommodation?", "It was designed for exactly that. Operators tell us the Luxury Series photographs like an architectural build and commands nightly rates well above standard cabins."],
      ["Can I customise the palette?", "Yes. Choose between two curated palettes — Coastal Light and Outback Dusk — or work with our team on custom joinery and finishes during your design consultation."],
    ],
  },
  {
    slug: "family-series",
    name: "Family Series Expandable Home",
    series: "Grand Range",
    badge: "Family Pick",
    tagline: "Three bedrooms. Real storage. Built for the everyday.",
    intro:
      "Designed with Australian families, for Australian families: robust finishes, a bathtub, proper laundry, and storage in every room. The practical one — done beautifully.",
    price: 64900,
    priceNote: "delivered pricing quoted per postcode",
    bedrooms: 3,
    bathrooms: 2,
    sleeps: 7,
    closed: "12.0m × 2.5m",
    expanded: "12.0m × 6.6m",
    area: 78,
    height: "2.6m internal ceiling",
    weight: "≈ 10.1 tonnes",
    leadTime: "12–16 weeks",
    audience: ["Growing families", "Multi-generational living", "First home buyers", "Rural families"],
    palette: "day",
    features: [
      ["Storage everywhere", "Built-in robes in all three bedrooms, overhead kitchen cabinets, linen press and under-bench laundry storage."],
      ["A real family bathroom", "Full-size bathtub plus shower — rare in this category and the feature parents thank us for most."],
      ["Kid-proof finishes", "Scratch-resistant flooring, wipeable wall panels and rounded joinery edges throughout."],
      ["Zoned for sanity", "Bedrooms grouped away from living space, with the master separated for genuine privacy."],
    ],
    included: [
      "Structural steel frame, fully welded and galvanised",
      "100mm insulated wall, roof and floor panels",
      "Double-glazed windows and sliding doors",
      "Family kitchen with pantry and full-height fridge space",
      "Family bathroom with bathtub + separate ensuite",
      "Dedicated laundry nook with storage",
      "Built-in robes to all bedrooms",
      "Two reverse-cycle air conditioners",
      "Impact-resistant internal wall linings",
      "Vinyl plank flooring, fully finished throughout",
    ],
    upgrades: [
      ["Study nook joinery package", "from $2,900"],
      ["Bunk-room fit-out (sleeps 4)", "from $4,600"],
      ["Off-grid solar + battery package", "from $18,500"],
      ["Deck + covered outdoor play area", "from $12,800"],
      ["Furniture package (turnkey)", "from $11,900"],
    ],
    specs: [
      ["Transport dimensions", "12.0m L × 2.5m W × 2.9m H"],
      ["Expanded footprint", "12.0m L × 6.6m W"],
      ["Internal floor area", "78m²"],
      ["Structure", "Galvanised steel frame, insulated sandwich panels"],
      ["Wind rating", "Engineered to AS/NZS 1170 (site-specific tie-downs)"],
      ["Electrical", "240V hardwired, compliant switchboard"],
      ["Plumbing", "Standard connections for mains, tank or septic"],
      ["Warranty", "10-year structural, 2-year fixtures and fittings"],
    ],
    floorplan: [
      { x: 0, y: 0, w: 20, h: 100, label: "Master + Ensuite" },
      { x: 20, y: 0, w: 34, h: 100, label: "Living / Dining" },
      { x: 54, y: 0, w: 16, h: 100, label: "Kitchen / Pantry" },
      { x: 70, y: 0, w: 15, h: 50, label: "Bed 2" },
      { x: 70, y: 50, w: 15, h: 50, label: "Bed 3" },
      { x: 85, y: 0, w: 15, h: 100, label: "Bath / Laundry" },
    ],
    faqs: [
      ["How does the Family Series differ from the 40ft?", "Same footprint, different priorities: a bathtub, bigger pantry and laundry, built-in robes, tougher finishes and a bunk-ready third bedroom. It trades a little open space for a lot of practicality."],
      ["Can it handle a family long-term?", "Yes — it's engineered and specified as a permanent dwelling. Families use it as their primary residence while building, after downsizing, or simply as their home, full stop."],
      ["What about heating and cooling bills?", "Insulated panels and double glazing mean the two split systems rarely work hard. Most families report energy bills far below their previous house."],
    ],
  },
  {
    slug: "office-pod",
    name: "Office Pod",
    series: "Studio Range",
    badge: "Work From Home",
    tagline: "The commute is now eleven steps.",
    intro:
      "A dedicated, insulated, quiet workspace in your backyard. Delivered finished, powered and ready for your first video call within days.",
    price: 18900,
    priceNote: "delivered pricing quoted per postcode",
    bedrooms: 0,
    bathrooms: 0,
    sleeps: 0,
    closed: "3.6m × 2.4m",
    expanded: "3.6m × 2.4m (fixed module)",
    area: 8.6,
    height: "2.4m internal ceiling",
    weight: "≈ 2.1 tonnes",
    leadTime: "6–10 weeks",
    audience: ["Home offices", "Consultants", "Therapists & studios", "Small business"],
    palette: "day",
    features: [
      ["Acoustically treated", "Insulated panels and double glazing keep lawnmowers, dogs and household chaos out of your meetings."],
      ["Video-call ready", "Wall of glass for natural light, matte internal finishes that look sharp on camera, and cat-6 data points."],
      ["Climate controlled", "Reverse-cycle air conditioning as standard — comfortable at 8am in July and 3pm in January."],
      ["Under 10m² footprint", "Small enough to be exempt development in many council areas (always confirm locally — we help you check)."],
    ],
    included: [
      "Galvanised steel frame with insulated panels",
      "Full-width double-glazed glass sliding door",
      "Reverse-cycle split system air conditioner",
      "LED lighting with dimmer",
      "6 × power points + 2 × cat-6 data points",
      "Built-in desk-height cable management",
      "Vinyl plank flooring",
      "Externally rated 15A power inlet",
      "Security lockset",
      "Compliant switchboard with safety switches",
    ],
    upgrades: [
      ["Built-in desk + shelving joinery", "from $3,200"],
      ["Acoustic upgrade pack (music/podcast)", "from $4,500"],
      ["Kitchenette module", "from $3,900"],
      ["Heat-pump hot water + WC module", "from $8,900"],
      ["Solar + battery (off-grid office)", "from $9,500"],
    ],
    specs: [
      ["Module dimensions", "3.6m L × 2.4m W × 2.7m H"],
      ["Internal floor area", "8.6m²"],
      ["Structure", "Galvanised steel frame, insulated sandwich panels"],
      ["Glazing", "Double-glazed sliding door + fixed window"],
      ["Electrical", "240V, 15A caravan-style inlet"],
      ["Data", "2 × cat-6 outlets, conduit for fibre"],
      ["Placement", "Adjustable feet — most sites need no slab"],
      ["Warranty", "10-year structural, 2-year fixtures and fittings"],
    ],
    floorplan: [
      { x: 0, y: 0, w: 70, h: 100, label: "Workspace" },
      { x: 70, y: 0, w: 30, h: 100, label: "Storage Wall" },
    ],
    faqs: [
      ["Do I need council approval for an office pod?", "In many Australian council areas, structures under 10m² qualify as exempt development if they meet setback and height rules. Rules differ by state and council — we provide a checklist and help you confirm before you order."],
      ["How is it powered?", "A weatherproof 15A inlet connects to your house via a suitable outdoor circuit (your electrician can install one in about an hour), or go fully off-grid with the solar package."],
      ["Can it double as a guest room?", "Plenty of customers add a sofa bed. For regular guests, look at the Studio Pod — it adds a bathroom and kitchenette."],
    ],
  },
  {
    slug: "studio-pod",
    name: "Studio Pod",
    series: "Studio Range",
    badge: "Self-Contained",
    tagline: "A complete studio apartment. In your backyard.",
    intro:
      "Kitchenette, bathroom, sleeping zone and living space in one beautifully resolved module. The smartest way to add self-contained accommodation to any property.",
    price: 27900,
    priceNote: "delivered pricing quoted per postcode",
    bedrooms: 1,
    bathrooms: 1,
    sleeps: 2,
    closed: "6.0m × 2.5m",
    expanded: "6.0m × 2.5m (fixed module)",
    area: 15,
    height: "2.5m internal ceiling",
    weight: "≈ 3.4 tonnes",
    leadTime: "8–12 weeks",
    audience: ["Teen retreats", "Elderly parents", "Rental income", "Guest accommodation"],
    palette: "dusk",
    features: [
      ["Genuinely self-contained", "Bathroom with shower and toilet, kitchenette with cooktop and fridge space — a complete dwelling in 15m²."],
      ["One-day installation", "Arrives finished. Positioned, levelled and connected to services in a single day on most sites."],
      ["Designed to disappear", "Clean lines and muted cladding tones sit quietly in a backyard rather than dominating it."],
      ["Income ready", "Fitted to the standard renters expect — durable surfaces, proper ventilation, heating and cooling."],
    ],
    included: [
      "Galvanised steel frame with insulated panels",
      "Bathroom: shower, toilet, vanity, exhaust",
      "Kitchenette: sink, 2-burner cooktop, fridge space",
      "Double-glazed windows and sliding door",
      "Reverse-cycle split system air conditioner",
      "LED lighting and power points throughout",
      "Smoke alarm and compliant switchboard",
      "Vinyl plank flooring",
      "Hot water system",
      "External water, power and waste connections",
    ],
    upgrades: [
      ["Laundry provision package", "from $1,900"],
      ["Deck + privacy screen kit", "from $5,400"],
      ["Premium façade cladding", "from $3,600"],
      ["Furniture package (turnkey)", "from $4,900"],
      ["Solar + battery package", "from $11,500"],
    ],
    specs: [
      ["Module dimensions", "6.0m L × 2.5m W × 2.9m H"],
      ["Internal floor area", "15m²"],
      ["Structure", "Galvanised steel frame, insulated sandwich panels"],
      ["Wet areas", "Fully waterproofed to AS 3740"],
      ["Electrical", "240V, 15A inlet, compliant switchboard"],
      ["Plumbing", "Standard connections for mains, tank or septic"],
      ["Placement", "Adjustable feet or pier footings"],
      ["Warranty", "10-year structural, 2-year fixtures and fittings"],
    ],
    floorplan: [
      { x: 0, y: 0, w: 40, h: 100, label: "Sleep / Living" },
      { x: 40, y: 0, w: 32, h: 100, label: "Kitchenette" },
      { x: 72, y: 0, w: 28, h: 100, label: "Bathroom" },
    ],
    faqs: [
      ["Is the Studio Pod approved as a granny flat?", "It can be, depending on your state's secondary dwelling rules. In NSW, for example, secondary dwellings on eligible blocks can be approved quickly through complying development. We supply the documentation your certifier needs."],
      ["Can I rent it out?", "In most states yes, once approved as a secondary dwelling. Many customers cover their repayments with the rent — see our finance page for worked examples."],
      ["How is hot water handled?", "A compact electric hot water system is included; a heat-pump upgrade is available for lower running costs."],
    ],
  },
  {
    slug: "airbnb-cabin",
    name: "Airbnb Cabin",
    series: "Host Range",
    badge: "Investor Favourite",
    tagline: "Built to be booked.",
    intro:
      "Every decision — the glass wall, the outdoor shower point, the coffee nook, the linen storage — was made to earn five-star reviews and premium nightly rates.",
    price: 42900,
    priceNote: "delivered pricing quoted per postcode",
    bedrooms: 1,
    bathrooms: 1,
    sleeps: 3,
    closed: "7.2m × 2.5m",
    expanded: "7.2m × 5.4m",
    area: 36,
    height: "2.6m internal ceiling + raked living ceiling",
    weight: "≈ 6.1 tonnes",
    leadTime: "10–14 weeks",
    audience: ["Airbnb investors", "Holiday accommodation", "Farm stays", "Wellness retreats"],
    palette: "forest",
    features: [
      ["The photo that gets the booking", "A full-height glass gable frames your view — the hero shot that makes guests stop scrolling."],
      ["Five-star touchpoints", "Rainfall shower, quality linen storage, coffee nook, USB-C bedside points and blockout blinds as standard."],
      ["Durable where it matters", "Commercial-grade flooring and tapware specified for high-turnover use."],
      ["Host-friendly by design", "Lockable owner's cupboard, external service access and easy-clean surfaces cut turnover time."],
    ],
    included: [
      "Structural steel frame, fully welded and galvanised",
      "Full-height glazed gable end with sliding doors",
      "Hotel-spec bathroom with rainfall shower",
      "Kitchenette with stone-look benchtop",
      "Queen bedroom zone + day-bed nook",
      "Reverse-cycle split system air conditioner",
      "Commercial-grade flooring and tapware",
      "Blockout blinds and sheers",
      "Lockable owner's storage cupboard",
      "External hot/cold shower point",
    ],
    upgrades: [
      ["Cedar-look hot tub + deck kit", "from $16,500"],
      ["Outdoor fire pit + seating kit", "from $4,200"],
      ["Full off-grid package (remote sites)", "from $19,500"],
      ["Turnkey host package (furniture + styling)", "from $9,800"],
      ["Second glazed gable (dual aspect)", "from $7,400"],
    ],
    specs: [
      ["Transport dimensions", "7.2m L × 2.5m W × 3.0m H"],
      ["Expanded footprint", "7.2m L × 5.4m W"],
      ["Internal floor area", "36m²"],
      ["Structure", "Galvanised steel frame, insulated sandwich panels"],
      ["Glazing", "Double-glazed full-height gable + windows"],
      ["Electrical", "240V, 15A inlet, compliant switchboard"],
      ["Plumbing", "Standard connections for mains, tank or septic"],
      ["Warranty", "10-year structural, 2-year fixtures and fittings"],
    ],
    floorplan: [
      { x: 0, y: 0, w: 38, h: 100, label: "Bedroom Zone" },
      { x: 38, y: 0, w: 36, h: 100, label: "Living / Glass Gable" },
      { x: 74, y: 0, w: 26, h: 55, label: "Kitchenette" },
      { x: 74, y: 55, w: 26, h: 45, label: "Bathroom" },
    ],
    faqs: [
      ["What returns do Airbnb cabins achieve?", "Returns depend entirely on location, occupancy and rate — regional NSW and VIC operators commonly report $180–$350 per night for architecturally styled cabins. Read our Best Tiny Homes for Airbnb guide for a full worked example."],
      ["Do I need approval to run it as short-stay accommodation?", "Short-stay rules vary by state and council (registration schemes, night caps, land zoning). We provide a compliance checklist per state and recommend confirming with your council before ordering."],
      ["How quickly can I be hosting?", "Typical timeline: order to delivery in 10–14 weeks, installation and connections within a week, styling and listing photos the week after. Many hosts take their first booking within four months of ordering."],
    ],
  },
];
